Feature/update templates
eol-uchile/eol_xblock_discussion pull request #2
Opened 2024-08-05 19:44 UTC by catalinaIlabaca

Se actualizaron las templates basadas en las del tema de eol-theme-2020, posterior a eso se eliminaron las referencias hacia el tema, actualizando una imagen y una referencia de una archivo.

2026-01-06 13:18 UTC, tomaspemora requested changes
Creo que queda más ordenado el PR si el primer commit mueve las templates a la carpeta final en que quedarán, que en este caso sería el https://github.com/eol-uchile/eol_xblock_discussion/pull/2/changes/1581f86c1abff834edd5672114f464ad845abb7e y luego se aplican cambios sobre esas templates como en https://github.com/eol-uchile/eol_xblock_discussion/pull/2/changes/f02957473026ffbd1dbe82286da4f943d3cf68a9, https://github.com/eol-uchile/eol_xblock_discussion/pull/2/changes/fc3865e7517ed3943a40ec786aeafc4ed0798f41, etc. En esa misma linea, si uno mira el PR completo con los 9 commits, la mayoría de las templates se movieron pero en el caso de `_discussion_inline.html` esta se elimina y agrega. Para que quede consistente considerar usar `git mv`. Quizás esto se arregla moviendo el commit que hace el `git mv` primero.

2026-01-06 13:18 UTC, tomaspemora commented on eoldiscussion/static/html/_thread_list_template.html
> -                    <option value="activity">${_("by recent activity")}</option>
No me quedan claros estos cambios de idioma. Vamos a dejarlo en español en duro? No estamos considerando traducciones desde el inglés en este bloque?

2026-01-06 13:49 UTC, catalinaIlabaca commented on eoldiscussion/static/html/_thread_list_template.html
> -                    <option value="activity">${_("by recent activity")}</option>
Por ahora no, pues en el el tema estaban en español, como lo dice el commit iguale a lo que estaba en el tema, estoy de acuerdo con que deberiamos agregar las traducciones a este repo

2026-01-06 13:57 UTC, tomaspemora commented on eoldiscussion/static/html/_thread_list_template.html
> -                    <option value="activity">${_("by recent activity")}</option>
hagamoslo en un siguiente PR.

2026-01-09 14:09 UTC, catalinaIlabaca commented
@tomaspemora Listo lo solicitado, converse con vicente porque aun sale como si el archivo hubiera sido eliminado y creado, pero al revisar el blame se mantiene el historial.

2026-01-09 15:59 UTC, fsologureng commented
@tomaspemora @catalinaIlabaca hasta donde yo entiendo, la convención es que la carpeta static es para templates que no son procesadas o para templates javascript (underscore), era imprescindible cambiarlas de lugar para que funcionaran?

2026-01-09 16:51 UTC, tomaspemora commented
> @tomaspemora @catalinaIlabaca hasta donde yo entiendo, la convención es que la carpeta static es para templates que no son procesadas o para templates javascript (underscore), era imprescindible cambiarlas de lugar para que funcionaran?

Creo que en el caso de los xblock es en static donde van las templates html procesadas también https://github.com/edx/cookiecutter-xblock/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.package_name%7D%7D/static/html/%7B%7Bcookiecutter.package_name%7D%7D.html

https://github.com/openedx/edx-cookiecutters/blob/master/cookiecutter-xblock/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.package_name%7D%7D/static/html/%7B%7Bcookiecutter.package_name%7D%7D.html

2026-01-09 16:57 UTC, fsologureng commented
> > @tomaspemora @catalinaIlabaca hasta donde yo entiendo, la convención es que la carpeta static es para templates que no son procesadas o para templates javascript (underscore), era imprescindible cambiarlas de lugar para que funcionaran?
> 
> Creo que en el caso de los xblock es en static donde van las templates html procesadas también https://github.com/edx/cookiecutter-xblock/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.package_name%7D%7D/static/html/%7B%7Bcookiecutter.package_name%7D%7D.html
> 
> https://github.com/openedx/edx-cookiecutters/blob/master/cookiecutter-xblock/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.package_name%7D%7D/static/html/%7B%7Bcookiecutter.package_name%7D%7D.html

Esos códigos son 2 años más antiguos que el 1er commit de este xblock, pero bueno, contesta la pregunta.

2026-01-09 17:10 UTC, tomaspemora commented
> > > @tomaspemora @catalinaIlabaca hasta donde yo entiendo, la convención es que la carpeta static es para templates que no son procesadas o para templates javascript (underscore), era imprescindible cambiarlas de lugar para que funcionaran?
> > 
> > 
> > Creo que en el caso de los xblock es en static donde van las templates html procesadas también https://github.com/edx/cookiecutter-xblock/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.package_name%7D%7D/static/html/%7B%7Bcookiecutter.package_name%7D%7D.html
> > https://github.com/openedx/edx-cookiecutters/blob/master/cookiecutter-xblock/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.package_name%7D%7D/static/html/%7B%7Bcookiecutter.package_name%7D%7D.html
> 
> Esos códigos son 2 años más antiguos que el 1er commit de este xblock, pero bueno, contesta la pregunta.

Esa estructura no ha cambiado hasta donde yo sé
https://docs.openedx.org/projects/xblock/en/latest/xblock-tutorial/anatomy/html.html

2026-01-09 17:25 UTC, fsologureng commented
> Esa estructura no ha cambiado hasta donde yo sé https://docs.openedx.org/projects/xblock/en/latest/xblock-tutorial/anatomy/html.html

https://github.com/openedx/xblock-sdk/tree/master/sample_xblocks/thumbs/static
>  Each XBlock can choose its directory structure, as long as it specifies the correct paths to importlib.resources.

Pero claramente es la estructura de facto :+1:

2026-01-12 14:40 UTC, tomaspemora requested changes
En mi opinión los commits:
- https://github.com/eol-uchile/eol_xblock_discussion/commit/652a60111ad7c20e8d61e8b737710e1f903f6072
- https://github.com/eol-uchile/eol_xblock_discussion/commit/79a98e2a764263ad14fd3fd9fc10e84ecd05bab9
- https://github.com/eol-uchile/eol_xblock_discussion/commit/d42a7ae20aba536294d49b53566965cb7879418d

Podrían squashearse bajo la consigna "mako templates"

2026-01-12 14:40 UTC, tomaspemora commented on eoldiscussion/static/html/_underscore_templates2.html
> -<%static:include path="/openedx/themes/eol-uchile-2020/lms/templates/discussion/templates2.underscore" />
esta linea se modifica en:
- https://github.com/eol-uchile/eol_xblock_discussion/commit/5884963a342190de620b349028d0c84a55c2197e#diff-c34a2eff958840c765c2b5612831bcefb6b77b983e46609f9e4d3e7282af38b8L23
- https://github.com/eol-uchile/eol_xblock_discussion/commit/d30eb63976718f333a0300575c474095670ded52#diff-c34a2eff958840c765c2b5612831bcefb6b77b983e46609f9e4d3e7282af38b8L23
- https://github.com/eol-uchile/eol_xblock_discussion/commit/79a98e2a764263ad14fd3fd9fc10e84ecd05bab9#diff-c34a2eff958840c765c2b5612831bcefb6b77b983e46609f9e4d3e7282af38b8L23-R23
- https://github.com/eol-uchile/eol_xblock_discussion/pull/2/changes/652a60111ad7c20e8d61e8b737710e1f903f6072#diff-c34a2eff958840c765c2b5612831bcefb6b77b983e46609f9e4d3e7282af38b8L23

Creo que es innecesario tener tantas modificaciones intermedias de ese archivo al menos en esa línea. Si hay una lógica como:
1. Cambio las templates de lugar
2. Reemplazo las templates actuales de este repo por las más actualizadas que vivían en el tema
3. Actualizó las templates al valor final con el que debe quedar en este repo

Me parece bien, pero me da la impresión de que hay modificaciones que están demás.

Por favor revisar si no hay otro caso similar.

2026-01-19 14:19 UTC, tomaspemora requested changes

2026-01-19 14:19 UTC, tomaspemora commented on setup.py
> -    package_data={"eoldiscussion": ["*.html","*.underscore"]}
esto lo movería con el primer commit

2026-01-19 18:16 UTC, tomaspemora approved these changes

2026-01-19 18:17 UTC, tomaspemora commented
diría que estamos ok para el merge @catalinaIlabaca confirmar por favor

2026-01-19 18:31 UTC, catalinaIlabaca commented
@tomaspemora confirmo correcto el squash

2026-01-19 18:32 UTC, merged